export const CHAT_THEME_IDS = ["light", "dark", "midnight", "glass"];

export const CHAT_THEMES = {
  light: {
    id: "light",
    name: "Light",
    chatBackground: "#ffffff",
    botBubble: "#f3f4f6",
    botText: "#374151",
    text: "#374151",
    inputBackground: "#ffffff",
    inputText: "#1f2937",
    panelBorder: "#e5e7eb",
    messagesArea: "#f8fafc",
    footerBackground: "#ffffff",
    footerBorder: "#f3f4f6",
    quickReplyBackground: "#ffffff",
    secondaryButtonBg: "#f8fafc",
    secondaryButtonText: "#475569",
    secondaryButtonBorder: "#e2e8f0",
    typingDotBg: null,
    glass: false,
    quickReplyShade: -50,
  },
  dark: {
    id: "dark",
    name: "Dark",
    chatBackground: "#1A1A1A",
    botBubble: "#2A2A2A",
    botText: "#ffffff",
    text: "#ffffff",
    inputBackground: "#111111",
    inputText: "#ffffff",
    panelBorder: "#333333",
    messagesArea: "#1A1A1A",
    footerBackground: "#1A1A1A",
    footerBorder: "#2A2A2A",
    quickReplyBackground: "#1A1A1A",
    secondaryButtonBg: "#2A2A2A",
    secondaryButtonText: "#d1d5db",
    secondaryButtonBorder: "#404040",
    typingDotBg: null,
    glass: false,
    quickReplyShade: 60,
  },
  midnight: {
    id: "midnight",
    name: "Midnight",
    chatBackground: "#0A0A0F",
    botBubble: "#1A1A2E",
    botText: "#E0E0FF",
    text: "#E0E0FF",
    inputBackground: "#0F0F1A",
    inputText: "#E0E0FF",
    panelBorder: "#2A2A4A",
    messagesArea: "#0A0A0F",
    footerBackground: "#0A0A0F",
    footerBorder: "#1A1A2E",
    quickReplyBackground: "#0A0A0F",
    secondaryButtonBg: "#1A1A2E",
    secondaryButtonText: "#c4c4e8",
    secondaryButtonBorder: "#2A2A4A",
    typingDotBg: null,
    glass: false,
    quickReplyShade: 60,
  },
  glass: {
    id: "glass",
    name: "Glass",
    chatBackground: "rgba(0,0,0,0.25)",
    botBubble: "rgba(0,0,0,0.3)",
    botText: "#ffffff",
    text: "#ffffff",
    inputBackground: "rgba(0,0,0,0.2)",
    inputText: "#ffffff",
    panelBorder: "rgba(255,255,255,0.2)",
    messagesArea: "rgba(0,0,0,0.15)",
    footerBackground: "rgba(0,0,0,0.2)",
    footerBorder: "rgba(255,255,255,0.15)",
    quickReplyBackground: "rgba(0,0,0,0.2)",
    secondaryButtonBg: "rgba(255,255,255,0.12)",
    secondaryButtonText: "#e5e5e5",
    secondaryButtonBorder: "rgba(255,255,255,0.25)",
    typingDotBg: null,
    glass: true,
    quickReplyShade: 50,
  },
};

export function getChatTheme(themeId) {
  return CHAT_THEMES[themeId] ?? CHAT_THEMES.light;
}

/** @param {string} themeId @param {string} brandColor */
export function resolveChatTheme(themeId, brandColor) {
  const theme = getChatTheme(themeId);
  return {
    ...theme,
    brandColor,
    userBubble: brandColor,
    userText: "#ffffff",
  };
}
